# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a000sap', models.CharField(max_length=25)),
                ('codigo_unico', models.CharField(max_length=25)),
                ('visitas', models.IntegerField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('direccion_fisica', models.CharField(max_length=2000)),
                ('direccion_fiscal', models.CharField(max_length=2000)),
                ('persona_contacto', models.CharField(max_length=70)),
                ('correo_tienda', models.CharField(max_length=70)),
                ('correo_empresario', models.CharField(max_length=70)),
                ('telefono_empresario', models.CharField(max_length=20)),
                ('telefono_tienda', models.CharField(max_length=20)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('empleados', models.IntegerField()),
                ('punto_rojo', models.BooleanField(default=False)),
                ('caso_remedy', models.CharField(max_length=25)),
                ('aprobacion_1', models.CharField(max_length=25, null=True)),
                ('aprobacion_2', models.CharField(max_length=25, null=True)),
                ('rechazado', models.CharField(max_length=25, null=True)),
                ('idop_solicitante', models.CharField(max_length=10)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('enero', models.BooleanField(default=False)),
                ('febrero', models.BooleanField(default=False)),
                ('marzo', models.BooleanField(default=False)),
                ('abril', models.BooleanField(default=False)),
                ('mayo', models.BooleanField(default=False)),
                ('junio', models.BooleanField(default=False)),
                ('julio', models.BooleanField(default=False)),
                ('agosto', models.BooleanField(default=False)),
                ('septiembre', models.BooleanField(default=False)),
                ('octubre', models.BooleanField(default=False)),
                ('noviembre', models.BooleanField(default=False)),
                ('diciembre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CentroRecarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_recarga', models.CharField(max_length=50)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=200)),
                ('capital', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CodigoDeudor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_deudor', models.CharField(max_length=10)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinador', models.CharField(max_length=50)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=1000)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribuidor', models.CharField(max_length=200)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerente', models.CharField(max_length=50)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a000sap', models.CharField(max_length=25, null=True)),
                ('codigo_unico', models.CharField(max_length=25, null=True)),
                ('visitas', models.IntegerField(null=True)),
                ('latitud', models.FloatField(null=True)),
                ('longitud', models.FloatField(null=True)),
                ('direccion_fisica', models.CharField(max_length=2000, null=True)),
                ('direccion_fiscal', models.CharField(max_length=2000, null=True)),
                ('persona_contacto', models.CharField(max_length=70, null=True)),
                ('correo_tienda', models.CharField(max_length=70, null=True)),
                ('correo_empresario', models.CharField(max_length=70, null=True)),
                ('telefono_empresario', models.CharField(max_length=20, null=True)),
                ('telefono_tienda', models.CharField(max_length=20, null=True)),
                ('hora_apertura', models.TimeField(null=True)),
                ('hora_cierre', models.TimeField(null=True)),
                ('empleados', models.IntegerField(null=True)),
                ('punto_rojo', models.BooleanField()),
                ('caso_remedy', models.CharField(max_length=25, null=True)),
                ('fecha', models.DateField(null=True)),
                ('enero', models.BooleanField(default=False)),
                ('febrero', models.BooleanField(default=False)),
                ('marzo', models.BooleanField(default=False)),
                ('abril', models.BooleanField(default=False)),
                ('mayo', models.BooleanField(default=False)),
                ('junio', models.BooleanField(default=False)),
                ('julio', models.BooleanField(default=False)),
                ('agosto', models.BooleanField(default=False)),
                ('septiembre', models.BooleanField(default=False)),
                ('octubre', models.BooleanField(default=False)),
                ('noviembre', models.BooleanField(default=False)),
                ('diciembre', models.BooleanField(default=False)),
                ('centro_recarga_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.CentroRecarga')),
                ('codigo_deudor_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.CodigoDeudor')),
                ('coordinador_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Coordinador')),
                ('direccion_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Direccion')),
                ('distribuidor_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Distribuidor')),
                ('estado_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Estados')),
                ('gerente_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Gerente')),
            ],
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lider', models.CharField(max_length=50)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=100)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=25)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parroquias',
            fields=[
                ('id_parroquia', models.AutoField(primary_key=True, serialize=False)),
                ('parroquia', models.CharField(max_length=250)),
                ('id_municipio', models.ForeignKey(db_column='id_municipio', on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Municipios')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=25)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=10)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a000sap', models.CharField(max_length=25, null=True)),
                ('codigo_unico', models.CharField(max_length=25, null=True)),
                ('visitas', models.IntegerField(null=True)),
                ('latitud', models.CharField(max_length=20, null=True)),
                ('longitud', models.CharField(max_length=20, null=True)),
                ('direccion_fisica', models.CharField(max_length=2000, null=True)),
                ('direccion_fiscal', models.CharField(max_length=2000, null=True)),
                ('persona_contacto', models.CharField(max_length=70, null=True)),
                ('correo_tienda', models.CharField(max_length=70, null=True)),
                ('correo_empresario', models.CharField(max_length=70, null=True)),
                ('telefono_empresario', models.CharField(max_length=20, null=True)),
                ('telefono_tienda', models.CharField(max_length=20, null=True)),
                ('hora_apertura', models.TimeField(null=True)),
                ('hora_cierre', models.TimeField(null=True)),
                ('empleados', models.IntegerField(null=True)),
                ('punto_rojo', models.BooleanField(default=False)),
                ('caso_remedy', models.CharField(blank=True, max_length=25, null=True)),
                ('enero', models.BooleanField(default=False)),
                ('febrero', models.BooleanField(default=False)),
                ('marzo', models.BooleanField(default=False)),
                ('abril', models.BooleanField(default=False)),
                ('mayo', models.BooleanField(default=False)),
                ('junio', models.BooleanField(default=False)),
                ('julio', models.BooleanField(default=False)),
                ('agosto', models.BooleanField(default=False)),
                ('septiembre', models.BooleanField(default=False)),
                ('octubre', models.BooleanField(default=False)),
                ('noviembre', models.BooleanField(default=False)),
                ('diciembre', models.BooleanField(default=False)),
                ('centro_recarga_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.CentroRecarga')),
                ('codigo_deudor_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.CodigoDeudor')),
                ('coordinador_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Coordinador')),
                ('direccion_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Direccion')),
                ('distribuidor_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Distribuidor')),
                ('estado_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Estados')),
                ('gerente_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Gerente')),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lider_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Lider')),
                ('municipio_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Municipios')),
                ('nombre_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Nombre')),
                ('oficina_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Oficina')),
                ('region_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Region')),
                ('rif_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Rif')),
                ('status_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=5)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aa', models.CharField(max_length=100)),
                ('ldap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='temporal',
            name='tipo_aa_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.TipoAa'),
        ),
        migrations.AddField(
            model_name='temporal',
            name='tipo_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Tipo'),
        ),
        migrations.AddField(
            model_name='historico',
            name='lider_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Lider'),
        ),
        migrations.AddField(
            model_name='historico',
            name='municipio_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Municipios'),
        ),
        migrations.AddField(
            model_name='historico',
            name='nombre_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Nombre'),
        ),
        migrations.AddField(
            model_name='historico',
            name='oficina_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Oficina'),
        ),
        migrations.AddField(
            model_name='historico',
            name='region_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Region'),
        ),
        migrations.AddField(
            model_name='historico',
            name='rif_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Rif'),
        ),
        migrations.AddField(
            model_name='historico',
            name='status_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Status'),
        ),
        migrations.AddField(
            model_name='historico',
            name='tipo_aa_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.TipoAa'),
        ),
        migrations.AddField(
            model_name='historico',
            name='tipo_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Tipo'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Estados'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='centro_recarga_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.CentroRecarga'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='codigo_deudor_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.CodigoDeudor'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='coordinador_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Coordinador'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='direccion_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Direccion'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='distribuidor_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Distribuidor'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='estado_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Estados'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='gerente_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Gerente'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='lider_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Lider'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='municipio_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Municipios'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='nombre_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Nombre'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='oficina_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Oficina'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='region_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Region'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='rif_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Rif'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='status_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Status'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='tipo_aa_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.TipoAa'),
        ),
        migrations.AddField(
            model_name='cambio',
            name='tipo_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jerarquia.Tipo'),
        ),
    ]
