# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 14:20

from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('fecha_actividad', models.DateField()),
                ('plataforma', models.CharField(max_length=50)),
                ('tecnologia', models.CharField(max_length=50)),
                ('terminal', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('fecha_actividad', models.DateField()),
                ('plataforma', models.CharField(max_length=50)),
                ('tecnologia', models.CharField(max_length=50)),
                ('terminal', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('fecha_actividad', models.DateField()),
                ('plataforma', models.CharField(max_length=50)),
                ('tecnologia', models.CharField(max_length=50)),
                ('terminal', models.CharField(max_length=50)),
                ('bruta', models.IntegerField()),
                ('neta', models.IntegerField()),
                ('reactivada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_coord', models.CharField(max_length=255, null=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('fecha_cuota', models.DateField()),
                ('cuota_activaciones_total', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_total', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_sp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_nosp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_prepago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_pospago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_spmp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_spme', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_nospmp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_nospme', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_spprepago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_sppospago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_nospprepago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_activaciones_nosppospago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_sp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_nosp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_prepago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_pospago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_spmp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_spme', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_nospmp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_nospme', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_spprepago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_sppospago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_nospprepago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_altas_nosppospago', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_cater_spmp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_cater_spme', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_cater_nospmp', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_cater_nospme', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_tvhd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_tvsd', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cuota_fijo', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dir', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gte', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Homologador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homologador', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('coordinador_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteria.Coordinador')),
                ('gerente_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteria.Gerente')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre_local', models.CharField(max_length=255, null=True)),
                ('codigo_sap', models.CharField(max_length=70, null=True)),
                ('cc', models.CharField(max_length=50)),
                ('canal', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=False)),
                ('direccion_fisica', models.CharField(max_length=255)),
                ('jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteria.Jerarquia')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_plan', models.CharField(max_length=20)),
                ('nombre_plan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProduccionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prod', models.DateField()),
                ('renta_mensual', models.FloatField()),
                ('recarga_plan', models.FloatField()),
                ('homologador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteria.Homologador')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteria.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_super', models.CharField(max_length=255, null=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteria.Direccion')),
                ('estado_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteria.Estado')),
                ('region_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteria.Region')),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteria.Ubicacion'),
        ),
        migrations.AddField(
            model_name='jerarquia',
            name='supervisor_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteria.Supervisor'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='local_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteria.Local'),
        ),
        migrations.AddField(
            model_name='baja',
            name='local_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteria.Local'),
        ),
        migrations.AddField(
            model_name='baja',
            name='plan_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteria.ProduccionPlan'),
        ),
        migrations.AddField(
            model_name='alta',
            name='local_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteria.Local'),
        ),
        migrations.AddField(
            model_name='alta',
            name='plan_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteria.ProduccionPlan'),
        ),
        migrations.AddField(
            model_name='activacion',
            name='local_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteria.Local'),
        ),
        migrations.AddField(
            model_name='activacion',
            name='plan_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteria.ProduccionPlan'),
        ),
    ]
